# Generated by Django 3.2.9 on 2022-01-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='books',
            field=models.ManyToManyField(related_name='products', to='shop.Book'),
        ),
    ]
